
# nome da pipeline
name: 'Execução Manual'

#gatilhos / triggers -regras de disparo
#gatilho manual = workflow_dipatch

on:
  workflow_dispatch:

#tarefas dentro da pipeline = jobs

jobs:

#nome do job

e2e-tests:
#maquina onde o job vai rodar

runs-on: ubuntu-latest

 #passos do job
steps:
 #clone do projeto
   -uses: actions/checkout@v4

  #instalação do node
   -name: 'Instalação do Node'
   uses: actions/setup-node@v4
   with:
        node-version: 24.x 

  #instalação do Yarn
   -name: 'Instalação do Yarn'
   run: npm install -g yarn

  #  instalação das dependências do projeto
   -name: 'Instalação das dependências do projeto'
   run: yarn 


  #instalação do browsers do Playwright
   -name: 'Instalação dos browsers do Playwright'
   run: yarn add playwright install

  #execução dos testes
   -name: 'Execução dos testes'
   run: yarn run e2e
    